[database]
driver = "mysql"
dbName = "vcommerce"
Id = "vcommerce"
password = "Abcde!2345"
ipAddress = "localhost"
port = 8089
maxOpenConnection = 10
maxIdleConnection = 10

[echo]
port = 8600

[api]
handleTimeoutMS = 1000
sellerUploadFilePath = "/vcom/backend/api/download"

[asset]
userProfileImageSavePath = "/vcom/backend/asset/profile"

[firebase]
serviceAccountKeyPath = "/vcom/backend/api/firebase_adminsdk.json"

[log]
stdOut = false
enable = true
level = "DEBUG"
filename = "/vcom/backend/api/log/vcommerce.log"
maxSize = 100
maxAge = 7
