[database]
driver = "mysql"
dbName = "vcommerce"
Id = "vcommerce"
password = "Abcde!2345"
ipAddress = "localhost"
port = 8089
maxOpenConnection = 10
maxIdleConnection = 10

[echo]
port = 8600

[api]
handleTimeoutMS = 1000

[log]
stdOut = true
enable = true
level = "DEBUG"
filename = "/vcom/backend-second/log/vcommerce.log"
maxSize = 100
maxAge = 7
